### ISSUE TITLE
War3Api.Object throwing InvalidOperationException even when collection was not modified

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Api#18]
The following code:

```
    public static void CheckAbilityIntegrity(Map map)
    {
      List<Ability> abilities = new();
      var objectDatabase = GetObjectDatabaseFromMap(map);
      var units = objectDatabase.GetUnits();
      foreach (var unit in units)
      {
        if (unit.IsAbilitiesNormalModified)
        {
          foreach (var ability in unit.AbilitiesNormal)
          {
            
          }
        }
      }
    }
```

Produces the following exception:
```
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at War3Api.Object.InternalExtensions.CastWhere[TKey,TValue,TResult](Dictionary`2 source)+MoveNext() in C:\Users\Zak\source\repos\AzerothWarsCSharpNew\src\War3Api.Object\InternalExtensions.cs:line 21
   at AzerothWarsCSharp.Launcher.IntegrityChecker.CheckAbilityIntegrity(Map map) in C:\Users\Zak\source\repos\AzerothWarsCSharpNew\src\AzerothWarsCSharp.Launcher\IntegrityChecker.cs:line 14
   at AzerothWarsCSharp.Launcher.Program.CheckMapIntegrity(String baseMapPath) in C:\Users\Zak\source\repos\AzerothWarsCSharpNew\src\AzerothWarsCSharp.Launcher\Program.cs:line 99
   at AzerothWarsCSharp.Launcher.Program.MakeDecision() in C:\Users\Zak\source\repos\AzerothWarsCSharpNew\src\AzerothWarsCSharp.Launcher\Program.cs:line 87
   at AzerothWarsCSharp.Launcher.Program.Main() in C:\Users\Zak\source\repos\AzerothWarsCSharpNew\src\AzerothWarsCSharp.Launcher\Program.cs:line 60
```

However, as can be seen from the method, the collection is never modified.

**Comment by Drake53** [comment]
GetUnits() uses CastWhere, which filters on all database _objects (abilities/units/etc) then casts only the units to unit, so you are enumerating over the _objects collection.

When you get the unit.AbiltiesNormal property, you have the following stacktrace:
- DataConverterNew.ToIEnumerableAbility
- DataConverterNew.ToAbility
- ObjectDatabaseBase.GetAbility
- ObjectDatabaseBase.GetObject
- ObjectDatabase.TryGetObject
- LazyStandardObjectDatabase.TryGetObject
- LazyStandardObjectDatabase.TryLoadObject
- LazyStandardObjectDatabase.LoadObject
- AbilityLoader.Load

Now that the ability was loaded in the (fallback) lazy db, it is also added to your own db using BaseObject.ShallowCopy (in ObjectDatabase.TryGetObject). This modifies _objects.

The solution is simple, use ToArray() or ToList() after GetUnits().

**Comment by YakaryBovine** [comment]
Cool, that makes sense, thank you. Adding .ToList() solved that issue.
